import type { KanjiPrediction } from "./types";

/**
 * Mock UI-only — chưa gọi API thật.
 * TODO(BE): thay bằng kết quả từ POST /api/kanji/recognize
 */
export const MOCK_PREDICTIONS: KanjiPrediction[] = [
  {
    kanji: "学",
    id: 123,
    json_id: 123,
    train_index: 12,
    confidence: 0.91,
    hiragana: "ガク、まなぶ",
    reading_on: ["ガク"],
    reading_kun: ["まな.ぶ"],
    meaning_vi: "học",
    meaning_hv: "HỌC",
    meaning_en: "study, learning",
    example: "学生 (がくせい) — học sinh",
    description: "Chữ Học — gồm bộ Tử (子) dưới mái nhà, ý nghĩa học tập, trường học.",
    tags: ["giáo dục", "trường học"],
    jlpt: "N5",
    strokes: 8,
    radical_number: 39,
    frequency: 63,
  },
  {
    kanji: "字",
    id: 88,
    json_id: 88,
    train_index: 45,
    confidence: 0.043,
    hiragana: "ジ、あざ",
    reading_on: ["ジ"],
    reading_kun: ["あざ", "あざな"],
    meaning_vi: "chữ, ký tự",
    meaning_hv: "TỰ",
    meaning_en: "character, letter",
    example: "漢字 (かんじ) — chữ Hán",
    description: "Chữ Tự — con (子) dưới mái nhà (宀), chỉ ký tự, chữ viết.",
    tags: ["ngôn ngữ"],
    jlpt: "N5",
    strokes: 6,
    radical_number: 39,
    frequency: 210,
  },
  {
    kanji: "覚",
    id: 201,
    json_id: 201,
    train_index: 132,
    confidence: 0.021,
    hiragana: "カク、おぼえる",
    reading_on: ["カク"],
    reading_kun: ["おぼ.える", "さ.める"],
    meaning_vi: "nhớ, nhận thức",
    meaning_hv: "GIÁC",
    meaning_en: "memorize, remember",
    example: "覚える (おぼえる) — ghi nhớ",
    description: "Chữ Giác — học (学) + thấy (見), nghĩa là nhận biết, ghi nhớ.",
    tags: ["nhận thức"],
    jlpt: "N4",
    strokes: 12,
    radical_number: 147,
    frequency: 540,
  },
  {
    kanji: "季",
    id: 150,
    json_id: 150,
    train_index: 98,
    confidence: 0.012,
    hiragana: "キ",
    reading_on: ["キ"],
    reading_kun: [],
    meaning_vi: "mùa",
    meaning_hv: "QUÝ",
    meaning_en: "seasons",
    example: "季節 (きせつ) — mùa, thời tiết",
    description: "Chữ Quý — lúa (禾) + con (子), chỉ mùa trong năm.",
    tags: ["thời gian"],
    jlpt: "N4",
    strokes: 8,
    radical_number: 115,
    frequency: 890,
  },
  {
    kanji: "栄",
    id: 175,
    json_id: 175,
    train_index: 171,
    confidence: 0.008,
    hiragana: "エイ、さかえる",
    reading_on: ["エイ", "ヨウ"],
    reading_kun: ["さか.える", "は.える"],
    meaning_vi: "vinh quang, phồn vinh",
    meaning_hv: "VINH",
    meaning_en: "prosperity, glory",
    example: "栄養 (えいよう) — dinh dưỡng",
    description: "Chữ Vinh — hai ngọn lửa trên cây gỗ, ý phồn vinh.",
    tags: ["trừu tượng"],
    jlpt: "N4",
    strokes: 9,
    radical_number: 75,
    frequency: 1120,
  },
];

export const MOCK_MESSAGE = "Nhận diện thành công (dữ liệu demo UI — chưa gọi model thật).";
